### ISSUE TITLE
TarsActDemo中小bug

### ISSUE THREAD

**Issue by Titanssword** [TarsPHP/TarsPHP#12]
TarsPHP/examples/TarsActDemo/QD.ActHttpServer/src/model/ActCommentModel.php
TarsPHP/examples/TarsActDemo/QD.ActHttpServer/src/model/UserInfoModel.php

在以上两个文件中，关于serverIp 的地址有问题。
![image](https://user-images.githubusercontent.com/9337319/50636747-480d8c00-0f92-11e9-87c6-8d74a86092b1.png)

$commonIn->serverIp = '127.0.01';
这里IP地址写错。

**Comment by meijing0114** [comment]
感谢，你可以提patch，我们审核无问题后合入代码。

**Comment by bobzhangyong** [comment]
fixed
