### ISSUE TITLE
tars-websocket-server 这个demo websoket 连接失败，demo无法跑通。下面是报错日志

### ISSUE THREAD

**Issue by iiCircle** [TarsPHP/TarsPHP#18]
PHP Notice:  Undefined offset: 2 in /usr/local/app/tars/tarsnode/data/PHPTest.PHPWebsocketServer/bin/src/vendor/phptars/tars-server/src/protocol/HTTPProtocol.php on line 33

测试代码使用：client文件里面的 client1.html

**Comment by iiCircle** [comment]
访问 http://** ip ***/Index/index  可以收到回复 index success!!

**Comment by copyrenzhe** [comment]
1. 确保 私有模板里的 servType=websocket
2. 如果用nginx代理，不要用http协议
