### ISSUE TITLE
tars-http-server demo测试部分http情况跑不通，下面是日志。

### ISSUE THREAD

**Issue by iiCircle** [TarsPHP/TarsPHP#19]
下面的这个请求失败。actionIndex，actionTestHeader，actionTestStatus，actionPost1 可以正常运行。

// curl "172.17.0.3:28887/Index/testSelf?a=b" -i
    public function actionTestSelf()
    {
        $config = new CommunicatorConfig();
        $config->setLocator(ENVConf::getLocator());
        $config->setModuleName('PHPTest.PHPHttpServer');
        $config->setSocketMode(3);

        $servant = new TestTafServiceServant($config);
        $result = $servant->testSelf();

        $this->sendRaw('result:'.$result);
    }

 
PHP Fatal error:  Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php:87
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(370): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/controller/IndexController.php(110): HttpServer\servant\PHPTest\PHPServer\obj\TestTafServiceServant->testProperty()
#2 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Event.php(111): HttpServer\controller\IndexController->actionTestProperty()
#3 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(489): Tars\core\Event->onRequest(Object(Tars\core\Request), Object(Tars\core\Response))
#4 {main}
  thrown in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php on line 87
[2019-03-05 17:01:44 *9727.1]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php:87
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(370): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/controller/IndexController.php(110):

**Comment by bobzhangyong** [comment]
像主控寻址失败，建议你 在controller中 var_dump(ENVConf::getLocator()) 查看主控ip 和端口，确认是否可以telnet 通， 如果端口正常，建议var_dump Communicate 中 64行，检查寻址返回的IP 和端口

**Comment by meijing0114** [comment]
"PHPTest/PHPServer" 这个服务部署了吗?

**Comment by dreamsoday** [comment]
你这个报错解决了吗？我遇到的问题和这个一样

**Comment by iiCircle** [comment]
你这边解决了吗？我测试还是不行。http可以正常访问

**Comment by iiCircle** [comment]
PHP Notice:  Undefined offset: 2 in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/protocol/HTTPProtocol.php on line 33
PHP Notice:  Undefined offset: 2 in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/protocol/HTTPProtocol.php on line 33
sh: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
PHP Fatal error:  Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php:87
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(352): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/controller/IndexController.php(96): HttpServer\servant\PHPTest\PHPServer\obj\TestTafServiceServant->testSelf()
#2 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Event.php(111): HttpServer\controller\IndexController->actionTestSelf()
#3 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(502): Tars\core\Event->onRequest(Object(Tars\core\Request), Object(Tars\core\Response))
#4 {main}
  thrown in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php on line 87
[2019-03-24 09:56:28 *9426.0]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php:87
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(352): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/controller/IndexController.php(96): 
sh: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
sh: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
Communicator monitor route failed servantName:tars.tarsproperty.PropertyObj

**Comment by iiCircle** [comment]
PHPTest.PHPHttpServer start  [32;40m [SUCCESS] [0m
[2019-03-24 02:05:49] tars_logger.INFO: stat/property/keepalive/config/logger service init start...  [] []
[2019-03-24 02:05:49] tars_logger.INFO: stat/property/keepalive/config/logger service init finish...  [] []
[2019-03-24 02:05:49] tars_logger.INFO: Server type http...  [] []
PHP Fatal error:  Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/ResponsePacket.php:22
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php(138): Tars\client\ResponsePacket->decode()
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(352): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#2 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/controller/IndexController.php(96): HttpServer\servant\PHPTest\PHPServer\obj\TestTafServiceServant->testSelf()
#3 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Event.php(111): HttpServer\controller\IndexController->actionTestSelf()
#4 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(502): Tars\core\Event->onRequest(Obj in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/ResponsePacket.php on line 22
[2019-03-24 10:06:02 *630.3]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/ResponsePacket.php:22
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php(138): Tars\client\ResponsePacket->decode()
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(352): Tars\client\Co
PHP Fatal error:  Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/ResponsePacket.php:22
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php(138): Tars\client\ResponsePacket->decode()
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(352): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#2 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/controller/IndexController.php(96): HttpServer\servant\PHPTest\PHPServer\obj\TestTafServiceServant->testSelf()
#3 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Event.php(111): HttpServer\controller\IndexController->actionTestSelf()
#4 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(502): Tars\core\Event->onRequest(Obj in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/ResponsePacket.php on line 22
[2019-03-24 10:06:31 *631.4]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/ResponsePacket.php:22
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php(138): Tars\client\ResponsePacket->decode()
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(352): Tars\client\Co
PHP Notice:  Undefined offset: 2 in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/protocol/HTTPProtocol.php on line 33
PHP Notice:  Undefined offset: 2 in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/protocol/HTTPProtocol.php on line 33

**Comment by iiCircle** [comment]
[2019-03-25 07:30:42] tars_logger.ERROR: Tars\core\{closure} All workers are not alive any more. [] []
============= Enter actionTestSelf()
============= ENVConf::getLocator() : tars.tarsregistry.QueryObj@tcp -h 172.17.0.3 -p 17890
 ==== _routeInfo : [{"sHost":"172.17.0.3","sProtocol":"tcp","iPort":"17890","iTimeout":"","bIp":"","sIp":"172.17.0.3"}]
========= id : PHPTest.PHPServer.obj
========= route : 172.17.0.3
========= route : 10006
========= route : 60000
========= route : 1
PHP Fatal error:  Uncaught Exception: Rout fail in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/ResponsePacket.php:22
Stack trace:
#0 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php(138): Tars\client\ResponsePacket->decode()
#1 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(352): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#2 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/controller/IndexController.php(98): HttpServer\servant\PHPTest\PHPServer\obj\TestTafServiceServant->testSelf()
#3 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Event.php(111): HttpServer\controller\IndexController->actionTestSelf()
#4 /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(502): Tars\core\Event->onRequest(Obj in /usr/local/app/tars/tarsnode/data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/ResponsePacket.php on line 22
[2019-03-25 07:36:22] tars_logger.ERROR: Tars\core\{closure} All workers are not alive any more. [] []

**Comment by iiCircle** [comment]
PHPTest.PHPServer start  [32;40m [SUCCESS] [0m
[2019-03-25 07:31:27] tars_logger.INFO: stat/property/keepalive/config/logger service init start...  [] []
 == tcp == _routeInfo : [{"sHost":"172.17.0.3","sProtocol":"tcp","iPort":"17890","iTimeout":"","bIp":"","sIp":"172.17.0.3"}]
===== tcp ==== id : tars.tarsstat.StatObj
==== tcp ===== route : 172.17.0.3
==== tcp ===== route : 10004
==== tcp ===== route : 60000
==== tcp ===== route : 1
 == tcp == _routeInfo : [{"sHost":"172.17.0.3","sProtocol":"tcp","iPort":"17890","iTimeout":"","bIp":"","sIp":"172.17.0.3"}]
===== tcp ==== id : tars.tarsproperty.PropertyObj
==== tcp ===== route : 172.17.0.3
==== tcp ===== route : 10005
==== tcp ===== route : 60000
==== tcp ===== route : 1
 == tcp == _routeInfo : [{"sHost":"172.17.0.3","sProtocol":"tcp","iPort":"17890","iTimeout":"","bIp":"","sIp":"172.17.0.3"}]
===== tcp ==== id : tars.tarsconfig.ConfigObj
==== tcp ===== route : 172.17.0.3
==== tcp ===== route : 10001
==== tcp ===== route : 60000
==== tcp ===== route : 1
[2019-03-25 07:31:27] tars_logger.INFO: stat/property/keepalive/config/logger service init finish...  [] []
[2019-03-25 07:31:27] tars_logger.INFO: Server type tcp...  [] []
[2019-03-25 07:31:38] tars_logger.ERROR: Tars\core\{closure} All workers are not alive any more. [] []
[2019-03-25 07:31:51] tars_logger.INFO: testSelf request: [] []
[2019-03-25 07:31:51] tars_logger.INFO: ENVConf::getLocator():tars.tarsregistry.QueryObj@tcp -h 172.17.0.3 -p 17890 [] []
 == tcp == _routeInfo : [{"sHost":"172.17.0.3","sProtocol":"tcp","iPort":"17890","iTimeout":"","bIp":"","sIp":"172.17.0.3"}]
===== tcp ==== id : Test.TarsStressServer.StressObj
[2019-03-25 07:34:18] tars_logger.ERROR: Tars\core\{closure} All workers are not alive any more. [] []

**Comment by copyrenzhe** [comment]
@iiCircle 需要部署Test.TarsStressServer.StressObj 服务，麻烦确认下这个服务是否已部署

**Comment by copyrenzhe** [comment]
https://github.com/TarsCloud/TarsJava/tree/master/examples/stress-server
