### ISSUE TITLE
Tars\log\LogServant->logger()日志函数调用log服务时解包失败

### ISSUE THREAD

**Issue by kuoshijia** [TarsPHP/TarsPHP#24]
抛出异常trace如图
![QQ图片20190627151836](https://user-images.githubusercontent.com/45053950/60245769-d8001300-98ef-11e9-937e-6771dbe5a104.png)

\Tars\client\Communicator::invoke(RequestPacket $requestPacket, $timeout, $sIp = '', $iPort = 0)的入参如下（通过base64encode(serialize(get_defined_vars()))打印）：
#23 {main}string(7320) "YTo0OntzOjEzOiJyZXF1ZXN0UGFja2V0IjtPOjI1OiJUYXJzXGNsaWVudFxSZXF1ZXN0UGFja2V0IjoxNDp7czoxMToiX2VuY29kZUJ1ZnMiO2E6NTp7czozOiJhcHAiO3M6NDoiFgJCQiI7czo2OiJzZXJ2ZXIiO3M6MTM6IiYLVXNlclNlcnZpY2UiO3M6NDoiZmlsZSI7czo3OiI2BWxvY2FsIjtzOjY6ImZvcm1hdCI7czo4OiJGBiVZJW0lZCI7czo2OiJidWZmZXIiO3M6NDg5NjoiWQABBwAAExhbMjAxOS0wNi0yNyAwNzoyMTo1M10gbG9jYWwuRVJST1I6IFN5bWZvbnlcQ29tcG9uZW50XERlYnVnXEV4Y2VwdGlvblxGYXRhbFRocm93YWJsZUVycm9yOiBUb28gZmV3IGFyZ3VtZW50cyB0byBmdW5jdGlvbiBBcHBcSHR0cFxDb250cm9sbGVyc1xSZWdpc3RlckNvbnRyb2xsZXI6OlNNU0NvZGUoKSwgMCBwYXNzZWQgYW5kIGV4YWN0bHkgMyBleHBlY3RlZCBpbiAvdXNyL2xvY2FsL2FwcC90YXJzL3RhcnNub2RlL2RhdGEvQkIuVXNlclNlcnZpY2UvYmluL3NyYy9hcHAvSHR0cC9Db250cm9sbGVycy9SZWdpc3RlckNvbnRyb2xsZXIucGhwOjMwIFN0YWNrIHRyYWNlOiAjMCBbaW50ZXJuYWwgZnVuY3Rpb25dOiBBcHBcSHR0cFxDb250cm9sbGVyc1xSZWdpc3RlckNvbnRyb2xsZXItPlNNU0NvZGUoKSAjMSAvdXNyL2xvY2FsL2FwcC90YXJzL3RhcnNub2RlL2RhdGEvQkIuVXNlclNlcnZpY2UvYmluL3NyYy92ZW5kb3IvaWxsdW1pbmF0ZS9jb250YWluZXIvQm91bmRNZXRob2QucGhwKDMyKTogY2FsbF91c2VyX2Z1bmNfYXJyYXkoQXJyYXksIEFycmF5KSAjMiAvdXNyL2xvY2FsL2FwcC90YXJzL3RhcnNub2RlL2RhdGEvQkIuVXNlclNlcnZpY2UvYmluL3NyYy92ZW5kb3IvaWxsdW1pbmF0ZS9jb250YWluZXIvQm91bmRNZXRob2QucGhwKDkwKTogSWxsdW1pbmF0ZVxDb250YWluZXJcQm91bmRNZXRob2Q6OklsbHVtaW5hdGVcQ29udGFpbmVyXHtjbG9zdXJlfSgpICMzIC91c3IvbG9jYWwvYXBwL3RhcnMvdGFyc25vZGUvZGF0YS9CQi5Vc2VyU2VydmljZS9iaW4vc3JjL3ZlbmRvci9pbGx1bWluYXRlL2NvbnRhaW5lci9Cb3VuZE1ldGhvZC5waHAoMzQpOiBJbGx1bWluYXRlXENvbnRhaW5lclxCb3VuZE1ldGhvZDo6Y2FsbEJvdW5kTWV0aG9kKE9iamVjdChMYXJhdmVsXEx1bWVuXEFwcGxpY2F0aW9uKSwgQXJyYXksIE9iamVjdChDbG9zdXJlKSkgIzQgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvdmVuZG9yL2lsbHVtaW5hdGUvY29udGFpbmVyL0JvdW5kTWV0aG9kLnBocCg2Myk6IElsbHVtaW5hdGVcQ29udGFpbmVyXEJvdW5kTWV0aG9kOjpjYWxsKE9iamVjdChMYXJhdmVsXEx1bWVuXEFwcGxpY2F0aW9uKSwgQXJyYXksIEFycmF5KSAjNSAvdXNyL2xvY2FsL2FwcC90YXJzL3RhcnNub2RlL2RhdGEvQkIuVXNlclNlcnZpY2UvYmluL3NyYy92ZW5kb3IvaWxsdW1pbmF0ZS9jb250YWluZXIvQm91bmRNZXRob2QucGhwKDI3KTogSWxsdW1pbmF0ZVxDb250YWluZXJcQm91bmRNZXRob2Q6OmNhbGxDbGFzcyhPYmplY3QoTGFyYXZlbFxMdW1lblxBcHBsaWNhdGlvbiksICdBcHBcXEh0dHBcXENvbnRyby4uLicsIEFycmF5LCAnU01TQ29kZScpICM2IC91c3IvbG9jYWwvYXBwL3RhcnMvdGFyc25vZGUvZGF0YS9CQi5Vc2VyU2VydmljZS9iaW4vc3JjL3ZlbmRvci9pbGx1bWluYXRlL2NvbnRhaW5lci9Db250YWluZXIucGhwKDU3Nik6IElsbHVtaW5hdGVcQ29udGFpbmVyXEJvdW5kTWV0aG9kOjpjYWxsKE9iamVjdChMYXJhdmVsXEx1bWVuXEFwcGxpY2F0aW9uKSwgJ0FwcFxcSHR0cFxcQ29udHJvLi4uJywgQXJyYXksICdTTVNDb2RlJykgIzcgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvcm91dGVzL3dlYi5waHAoNDApOiBJbGx1bWluYXRlXENvbnRhaW5lclxDb250YWluZXItPmNhbGwoJ0FwcFxcSHR0cFxcQ29udHJvLi4uJywgQXJyYXksICdTTVNDb2RlJykgIzggW2ludGVybmFsIGZ1bmN0aW9uXTogQ2xvc3VyZS0+e2Nsb3N1cmV9KCdTTVNDb2RlJywgT2JqZWN0KElsbHVtaW5hdGVcSHR0cFxSZXF1ZXN0KSkgIzkgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvdmVuZG9yL2lsbHVtaW5hdGUvY29udGFpbmVyL0JvdW5kTWV0aG9kLnBocCgzMik6IGNhbGxfdXNlcl9mdW5jX2FycmF5KE9iamVjdChDbG9zdXJlKSwgQXJyYXkpICMxMCAvdXNyL2xvY2FsL2FwcC90YXJzL3RhcnNub2RlL2RhdGEvQkIuVXNlclNlcnZpY2UvYmluL3NyYy92ZW5kb3IvaWxsdW1pbmF0ZS9jb250YWluZXIvQm91bmRNZXRob2QucGhwKDc4KTogSWxsdW1pbmF0ZVxDb250YWluZXJcQm91bmRNZXRob2Q6OklsbHVtaW5hdGVcQ29udGFpbmVyXHtjbG9zdXJlfSgpICMxMSAvdXNyL2xvY2FsL2FwcC90YXJzL3RhcnNub2RlL2RhdGEvQkIuVXNlclNlcnZpY2UvYmluL3NyYy92ZW5kb3IvaWxsdW1pbmF0ZS9jb250YWluZXIvQm91bmRNZXRob2QucGhwKDM0KTogSWxsdW1pbmF0ZVxDb250YWluZXJcQm91bmRNZXRob2Q6OmNhbGxCb3VuZE1ldGhvZChPYmplY3QoTGFyYXZlbFxMdW1lblxBcHBsaWNhdGlvbiksIE9iamVjdChDbG9zdXJlKSwgT2JqZWN0KENsb3N1cmUpKSAjMTIgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvdmVuZG9yL2lsbHVtaW5hdGUvY29udGFpbmVyL0NvbnRhaW5lci5waHAoNTc2KTogSWxsdW1pbmF0ZVxDb250YWluZXJcQm91bmRNZXRob2Q6OmNhbGwoT2JqZWN0KExhcmF2ZWxcTHVtZW5cQXBwbGljYXRpb24pLCBPYmplY3QoQ2xvc3VyZSksIEFycmF5LCBOVUxMKSAjMTMgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvdmVuZG9yL2xhcmF2ZWwvbHVtZW4tZnJhbWV3b3JrL3NyYy9Db25jZXJucy9Sb3V0ZXNSZXF1ZXN0cy5waHAoMjg5KTogSWxsdW1pbmF0ZVxDb250YWluZXJcQ29udGFpbmVyLT5jYWxsKE9iamVjdChDbG9zdXJlKSwgQXJyYXkpICMxNCAvdXNyL2xvY2FsL2FwcC90YXJzL3RhcnNub2RlL2RhdGEvQkIuVXNlclNlcnZpY2UvYmluL3NyYy92ZW5kb3IvbGFyYXZlbC9sdW1lbi1mcmFtZXdvcmsvc3JjL0NvbmNlcm5zL1JvdXRlc1JlcXVlc3RzLnBocCgyNjMpOiBMYXJhdmVsXEx1bWVuXEFwcGxpY2F0aW9uLT5jYWxsQWN0aW9uT25BcnJheUJhc2VkUm91dGUoQXJyYXkpICMxNSAvdXNyL2xvY2FsL2FwcC90YXJzL3RhcnNub2RlL2RhdGEvQkIuVXNlclNlcnZpY2UvYmluL3NyYy92ZW5kb3IvbGFyYXZlbC9sdW1lbi1mcmFtZXdvcmsvc3JjL0NvbmNlcm5zL1JvdXRlc1JlcXVlc3RzLnBocCgyMzMpOiBMYXJhdmVsXEx1bWVuXEFwcGxpY2F0aW9uLT5oYW5kbGVGb3VuZFJvdXRlKEFycmF5KSAjMTYgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvdmVuZG9yL2xhcmF2ZWwvbHVtZW4tZnJhbWV3b3JrL3NyYy9Db25jZXJucy9Sb3V0ZXNSZXF1ZXN0cy5waHAoMTY5KTogTGFyYXZlbFxMdW1lblxBcHBsaWNhdGlvbi0+aGFuZGxlRGlzcGF0Y2hlclJlc3BvbnNlKEFycmF5KSAjMTcgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvdmVuZG9yL2xhcmF2ZWwvbHVtZW4tZnJhbWV3b3JrL3NyYy9Db25jZXJucy9Sb3V0ZXNSZXF1ZXN0cy5waHAoNDE2KTogTGFyYXZlbFxMdW1lblxBcHBsaWNhdGlvbi0+TGFyYXZlbFxMdW1lblxDb25jZXJuc1x7Y2xvc3VyZX0oT2JqZWN0KElsbHVtaW5hdGVcSHR0cFxSZXF1ZXN0KSkgIzE4IC91c3IvbG9jYWwvYXBwL3RhcnMvdGFyc25vZGUvZGF0YS9CQi5Vc2VyU2VydmljZS9iaW4vc3JjL3ZlbmRvci9sYXJhdmVsL2x1bWVuLWZyYW1ld29yay9zcmMvQ29uY2VybnMvUm91dGVzUmVxdWVzdHMucGhwKDE3MSk6IExhcmF2ZWxcTHVtZW5cQXBwbGljYXRpb24tPnNlbmRUaHJvdWdoUGlwZWxpbmUoQXJyYXksIE9iamVjdChDbG9zdXJlKSkgIzE5IC91c3IvbG9jYWwvYXBwL3RhcnMvdGFyc25vZGUvZGF0YS9CQi5Vc2VyU2VydmljZS9iaW4vc3JjL3ZlbmRvci9sdW94aWFvanVuMTk5Mi9sYXJhdmVsLXRhcnMvc3JjL2NvbnRyb2xsZXIvTGFyYXZlbENvbnRyb2xsZXIucGhwKDUwKTogTGFyYXZlbFxMdW1lblxBcHBsaWNhdGlvbi0+ZGlzcGF0Y2goT2JqZWN0KElsbHVtaW5hdGVcSHR0cFxSZXF1ZXN0KSkgIzIwIC91c3IvbG9jYWwvYXBwL3RhcnMvdGFyc25vZGUvZGF0YS9CQi5Vc2VyU2VydmljZS9iaW4vc3JjL3ZlbmRvci9sdW94aWFvanVuMTk5Mi9sYXJhdmVsLXRhcnMvc3JjL2NvbnRyb2xsZXIvTGFyYXZlbENvbnRyb2xsZXIucGhwKDI1KTogTHhqXExhcmF2ZWxcVGFyc1xjb250cm9sbGVyXExhcmF2ZWxDb250cm9sbGVyLT5oYW5kbGUoKSAjMjEgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvdmVuZG9yL3BocHRhcnMvdGFycy1zZXJ2ZXIvc3JjL2NvcmUvRXZlbnQucGhwKDExMSk6IEx4alxMYXJhdmVsXFRhcnNcY29udHJvbGxlclxMYXJhdmVsQ29udHJvbGxlci0+YWN0aW9uUm91dGUoKSAjMjIgL3Vzci9sb2NhbC9hcHAvdGFycy90YXJzbm9kZS9kYXRhL0JCLlVzZXJTZXJ2aWNlL2Jpbi9zcmMvdmVuZG9yL3BocHRhcnMvdGFycy1zZXJ2ZXIvc3JjL2NvcmUvU2VydmVyLnBocCg1NDMpOiBUYXJzXGNvcmVcRXZlbnQtPm9uUmVxdWVzdChPYmplY3QoVGFyc1xjb3JlXFJlcXVlc3QpLCBPYmplY3QoVGFyc1xjb3JlXFJlc3BvbnNlKSkgIzIzIHttYWlufSB7ImV4Y2VwdGlvbiI6IltvYmplY3RdIChTeW1mb255XFxDb21wb25lbnRcXERlYnVnXFxFeGNlcHRpb25cXEZhdGFsVGhyb3dhYmxlRXJyb3IoY29kZTogMCk6IFRvbyBmZXcgYXJndW1lbnRzIHRvIGZ1bmN0aW9uIEFwcFxcSHR0cFxcQ29udHJvbGxlcnNcXFJlZ2lzdGVyQ29udHJvbGxlcjo6U01TQ29kZSgpLCAwIHBhc3NlZCBhbmQgZXhhY3RseSAzIGV4cGVjdGVkIGF0IC91c3IvbG9jYWwvYXBwL3RhcnMvdGFyc25vZGUvZGF0YS9CQi5Vc2VyU2VydmljZS9iaW4vc3JjL2FwcC9IdHRwL0NvbnRyb2xsZXJzL1JlZ2lzdGVyQ29udHJvbGxlci5waHA6MzApIn0gW10KIjt9czoxMToiX3JlcXVlc3RCdWYiO047czoxMjoiX3Jlc3BvbnNlQnVmIjtOO3M6ODoiX3NCdWZmZXIiO047czo5OiJfaVZlcnNpb24iO2k6MTtzOjEyOiJfc2VydmFudE5hbWUiO3M6MTk6InRhcnMudGFyc2xvZy5Mb2dPYmoiO3M6OToiX2Z1bmNOYW1lIjtzOjY6ImxvZ2dlciI7czoxMToiX2lSZXF1ZXN0SWQiO2k6MTtzOjEyOiJfY1BhY2tldFR5cGUiO2k6MDtzOjEzOiJfaU1lc3NhZ2VUeXBlIjtpOjA7czoxMjoiX3RhcnNUaW1lb3V0IjtpOjIwMDA7czo5OiJfaVRpbWVvdXQiO2k6MjtzOjk6Il9jb250ZXh0cyI7YTowOnt9czo5OiJfc3RhdHVzZXMiO2E6MDp7fX1zOjc6InRpbWVvdXQiO2k6MzAwMDtzOjM6InNJcCI7czowOiIiO3M6NToiaVBvcnQiO2k6MDt9"

**Comment by kuoshijia** [comment]
返回包为：\Tars\client\ResponsePacket对象
$_responseBuf（base64） “AAAAFBABLDABTFxtAAADDEYAeAw=”
$iVersion是1

**Comment by kuoshijia** [comment]
主要是红线部分调用报错了
![微信截图_20190703113910](https://user-images.githubusercontent.com/45053950/60561744-41b46d00-9d87-11e9-82ff-95c10e27b16e.png)

**Comment by kuoshijia** [comment]
帮忙看一下是什么错误@copyrenzhe

**Comment by copyrenzhe** [comment]
```php
$responseBuf = "AAAAFBABLDABTFxtAAADDEYAeAw=";
$buf = base64_decode($responseBuf);
$ret = \TUPAPI::decode($buf, 1);
var_dump($ret);
```

使用以上脚本测试是可以正常decode的，能使用下面命令提供一下phptars扩展的版本吗？
> **php --ri phptars**

**Comment by kuoshijia** [comment]
phptars version => 2.2.3 @copyrenzhe 
我用了你提供的脚本来测也是正常的，可能不是decode的问题，谢谢啦
