### ISSUE TITLE
composer打包打不了如何解决？

### ISSUE THREAD

**Issue by skylway** [TarsPHP/TarsPHP#26]
composer打包打不了如何解决？
composer.json文件没改过，试过换name还是不行

{
    "name" : "tars-http-server-demo",
    "description": "tars http server",
    "require": {
        "phptars/tars-server": "~0.3",
        "phptars/tars-deploy": "~0.1",
        "phptars/tars2php": "~0.1",
        "phptars/tars-log": "~0.1",
        "ext-zip" : ">=0.0.1"
    },
    "autoload": {
        "psr-4": {
            "HttpServer\\" : "./"
        }
    },
    "minimum-stability": "stable",
    "scripts" : {
        "deploy" : "\\Tars\\deploy\\Deploy::run"
    }
}

错误如下：
Deprecation warning: Your package name tars-http-server-demo is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error. Class \Tars\deploy\Deploy is not autoloadable, can not call deploy script

**Comment by skylway** [comment]
name 改成 "name" : "http-server/tars-http-server-demo",
报错：
Class \Tars\deploy\Deploy is not autoloadable, can not call deploy script

**Comment by bobzhangyong** [comment]
这个好像是composer 的问题，要不升级一下composer 的版本，或者试试用阿里云的composer 镜像， 我们这边复现不了。
