### ISSUE TITLE
两台虚拟机搭建的tars运行PHPTest调用服务时报错 Rout fail

### ISSUE THREAD

**Issue by seven1987** [TarsPHP/TarsPHP#28]
PHPTest中调用index/index是没问题的，调用index/testbasic就出错了，log中错误信息如下：
PHP Fatal error:  Uncaught Exception: Rout fail in /data/tarsnode_data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php:87
Stack trace:
#0 /data/tarsnode_data/PHPTest.PHPHttpServer/bin/src/servant/PHPTest/PHPServer/obj/TestTafServiceServant.php(111): Tars\client\Communicator->invoke(Object(Tars\client\RequestPacket), 3)
#1 /data/tarsnode_data/PHPTest.PHPHttpServer/bin/src/controller/IndexController.php(142): HttpServer\servant\PHPTest\PHPServer\obj\TestTafServiceServant->testBasic(true, 1, '333', NULL, Object(Exception), NULL)
#2 /data/tarsnode_data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Event.php(112): HttpServer\controller\IndexController->actionTestBasic()
#3 /data/tarsnode_data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-server/src/core/Server.php(543): Tars\core\Event->onRequest(Object(Tars\core\Request), 

Object(Tars\core\Response))
#4 {main}
  thrown in /data/tarsnode_data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php on line 87
[2019-08-05 09:43:14 *203.2]    ERROR   zm_deactivate_swoole (ERROR 503): Fatal error: Uncaught Exception: Rout fail in /data/tarsnode_data/PHPTest.PHPHttpServer/bin/src/vendor/phptars/tars-client/src/Communicator.php:87

**Comment by bobzhangyong** [comment]
寻址问题 检查  ENVConf::getLocator() 输出的主控地址是否可以访问

检查 communicator.php 67行左右的 $this->_routeInfo 值是什么

**Comment by copyrenzhe** [comment]
@seven1987 确认下是否安装了 Test.TarsStressServer 服务，PHPTest.PHPServer 有依赖该服务，如果没有安装的话，可以注释相关的调用代码
