### ISSUE TITLE
Tars框架，tars2php工具在TCP端针对多个不同的OBJ批量生成代码

### ISSUE THREAD

**Issue by oyJouokong** [TarsPHP/TarsPHP#29]
Tars框架，tars2php工具在TCP端针对多个不同的OBJ批量生成代码，因为可能一个TCP服务中，有多个小模块，这样要分开多个OBJ，现在支持多个OBJ访问，但是tars2php生成工具暂时不支持多个obj生成代码，希望能改进一下，因为如果是多个TCP服务的话，不想每添加一个tcp都改一下vendor的tars2php工具代码，谢谢！

**Comment by bobzhangyong** [comment]
应该不用改代码啊，每个obj 一个tars 文件就好了。建议不要跨obj 共享 struct

**Comment by oyJouokong** [comment]
> 应该不用改代码啊，每个obj 一个tars 文件就好了。建议不要跨obj 共享 struct

我没有共享struct，我的意思是，tars2php这个代码生成工具，不支持生成多个obj路径的文件夹

**Comment by bobzhangyong** [comment]
tars 设计是 一个tars 文件是一个obj ，所以如果是多个obj 话，需要多个tars 文件，多次生成，然后你把生成好的文件夹拷贝到一起。 不知道我回答的是不是你要的意思。不行你可以 微信群里 找我沟通一下

**Comment by oyJouokong** [comment]
> tars 设计是 一个tars 文件是一个obj ，所以如果是多个obj 话，需要多个tars 文件，多次生成，然后你把生成好的文件夹拷贝到一起。 不知道我回答的是不是你要的意思。不行你可以 微信群里 找我沟通一下

我明白你的意思，我也分成多个obj了，但是我想一键就能生成多个文件，自动放在一起，我现在是自己改写了tars2php.php文件，可以达到我的期望了，谢谢啦

**Comment by lanlin** [comment]
我也有相同的疑问 https://github.com/TarsPHP/tars2php/issues/10
