### ISSUE TITLE
使用docker安装的TARS平台创建的tarsphp始终无法启动

### ISSUE THREAD

**Issue by XerxesSultan** [TarsPHP/TarsPHP#33]
本人使用https://tarsphp.gitbook.io教程中的docker安装方式,安装好之后,打开管理平台新增example中的httpserver,完全按照教程使用。但是新增服务和发布该服务都无法启动成功。多次调整和更换配置都是一样无法启动。请问是什么原因？或者是还有什么细节忽略了      日志：PHPTest.PHPHttpServer_172.17.0.3		[alarm] down, server is inactive
PHPTest.PHPHttpServer_172.17.0.3		patch PHPTest.PHPHttpServer succ, version 57

**Comment by bobzhangyong** [comment]
如果服务无法启动，可以找到对应的机器，检查 php_error 和 项目日志
