### ISSUE TITLE
README.md开发guidlineservice.php错误

### ISSUE THREAD

**Issue by waynesun01** [TarsPHP/TarsPHP#34]
新建services.php文件,内容如下:
<?php  
// 以namespace的方式,在psr4的框架下对代码进行加载  
return array(  
 'namespaceName' => 'HttpServer\\', 
 'monitorStoreConf' => [
	 //'className' => Tars\monitor\cache\RedisStoreCache::class,
	 //'config' => [
		// 'host' => '127.0.0.1',  
		// 'port' => 6379,  
		// 'password' => ':'
	 //],
	 'className' => Tars\monitor\cache\SwooleTableStoreCache::class,
	 'config' => [
		 'size' => 40960
	 ]
 ]
);  
这里应该是 
return array(
'obj'=>array(
namespaceName' => 'HttpServer\\', 
……
)
)；
否则在tarsweb上服务部署时OBJ就不知道该填什么了

**Comment by bobzhangyong** [comment]
已经修复 感谢反馈
