### ISSUE TITLE
Tars协议中请求参数基于json序列化，整个包基于tars协议序列化

### ISSUE THREAD

**Issue by ThunderRussell** [TarsPHP/TarsPHP#40]
tarsgo中扩展了tars协议，当JSONVERSION version = 257时，tars协议包中的SBuffer以json序列化方式写入；
req := requestf.RequestPacket{
		IVersion:     s.version,
		CPacketType:  int8(ctype),
		IRequestId:   atomic.AddInt32(&msgID, 1),
		SServantName: s.name,
		SFuncName:    sFuncName,
		**SBuffer:      tools.ByteToInt8(buf),**  //buf基于json序列化
		ITimeout:     s.comm.Client.ReqDefaultTimeout,
		Context:      reqContext,
		Status:       status,
		IMessageType: msgType,
	}
其他字段已原有tars格式序列化
望tarsphp能尽快支持对应功能

**Comment by bobzhangyong** [comment]
TarsPHP/tars-server@e16a260ff51e3301439ce66556c2de086f591aa0

Done
