### ISSUE TITLE
监控这些是用在什么业务场景的？

### ISSUE THREAD

**Issue by dmf-code** [TarsPHP/TarsPHP#49]
现在服务监控和特性监控这些我在开发业务的时候都没怎么用到，想问一下具体是用在什么业务场景，解决什么痛点。谢谢

**Comment by bobzhangyong** [comment]
服务监控主要监控别人调用你服务的情况，监控自己服务的健康程度。比如你的服务突然挂了，或者耗时高了，客户端会感知到上报，最后汇总到你的服务监控上。 你还可以监控，一段时间你的服务被调用的数量，耗时等。

特性监控主要是自己服务的特性，比如服务占用的内存，cpu，占用的端口数等。

**Comment by dmf-code** [comment]
好的，谢谢
